### ISSUE TITLE
[Blocker] CiviCRM core analysis error 

### ISSUE THREAD

**Issue by prondubuisi** [prondubuisi/gsoc2019#6]
Running Psalm on CiviCRM core throws [errors ](https://pastebin.com/x8jhQ6H9), here is a sample of the Psalm.xml file https://pastebin.com/M1qW2R7U

@eileenmcnaughton @jackgleeson

**Comment by eileenmcnaughton** [comment]
does running with debug help? like here
https://github.com/vimeo/psalm/issues/441

I'm guessing it's a file it can't check & we need to exclude?

**Comment by prondubuisi** [comment]
On it @eileenmcnaughton

**Comment by prondubuisi** [comment]
Hello @eileenmcnaughton this is the result from passing --debug https://gist.github.com/prondubuisi/19abf949b3965b47a51184cd1fdf7d74

**Comment by eileenmcnaughton** [comment]
So it just stopped at Getting /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/CRM/Contribute/StateMachine/Search.php ?

**Comment by prondubuisi** [comment]
The file is truncated, can you click on view full file?

**Comment by eileenmcnaughton** [comment]
hmm not sure - but what did if fail on?

**Comment by prondubuisi** [comment]
Analyzing /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/CRM/Utils/Check/Message.php
PHP Fatal error:  Uncaught UnexpectedValueException: $this->isVisible should be in scope in /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php:1007
Stack trace:
#0 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(700): Psalm\Internal\Analyzer\ClassAnalyzer->checkPropertyInitialization(Object(Psalm\Codebase), Object(Psalm\Config), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Context), Object(Psalm\Context), Object(Psalm\Internal\Analyzer\MethodAnalyzer))
#1 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(174): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#2 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Ps in /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php on line 1007

Fatal error: Uncaught UnexpectedValueException: $this->isVisible should be in scope in /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php:1007
Stack trace:
#0 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(700): Psalm\Internal\Analyzer\ClassAnalyzer->checkPropertyInitialization(Object(Psalm\Codebase), Object(Psalm\Config), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Context), Object(Psalm\Context), Object(Psalm\Internal\Analyzer\MethodAnalyzer))
#1 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(174): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#2 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Ps in /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php on line 1007
coolife@coolife:~/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm$

**Comment by prondubuisi** [comment]
> hmm not sure - but what did if fail on?

The view full file is just at the top of the file

**Comment by eileenmcnaughton** [comment]
@prondubuisi do you have any thoughts on what the issue might be. I note it's private scope but being set without a setting from other function -that could relate?

**Comment by prondubuisi** [comment]
The error points to files within psalm, I might have to open an issue on the Psalm repo

**Comment by eileenmcnaughton** [comment]
well maybe search through the psalm codebase & see where the error is coming from. Do you have an IDE with a debugger? If so you can step through the psalm code

**Comment by prondubuisi** [comment]
I Use vscode, Any recommendations for for code editors with debuggers?

**Comment by eileenmcnaughton** [comment]
I swear by phpstom but it's not free - although it might be for 30 days?

**Comment by eileenmcnaughton** [comment]
yep it is https://www.jetbrains.com/phpstorm/download/#section=mac - give it a go

**Comment by prondubuisi** [comment]
@eileenmcnaughton the [bug](https://github.com/vimeo/psalm/issues/1713)  was with Psalm and it has been fixed, Here is a look from our first core errors
https://gist.github.com/prondubuisi/1243e07f8de78ecd205fd526f09d2c8e

**Comment by eileenmcnaughton** [comment]
Cool - might be worth putting up a few PRs to fix a handful just for familiarisation ?

**Comment by prondubuisi** [comment]
> Cool - might be worth putting up a few PRs to fix a handful just for familiarisation ?

Okay, will do just that
